import type { BrandCategory, Locale } from './types'

export const brandCopy = {
  'en-gb': {
    label:'The brand edit',title:'Good gifts start with a little discovery.',intro:'Explore brands selected around real interests. Browse our introduction or visit the brand directly.',all:'Explore all brands',directoryTitle:'Find a brand that feels right.',directoryIntro:'Beauty, home, creative gifts and everyday favourites. Delivery evidence determines the order, followed by this season’s editorial priorities.',visit:'Visit brand',explore:'Explore brand',unavailable:'This brand link is temporarily unavailable.',available:'Brands to explore',pending:'Paused shopping links',pendingIntro:'You can still read these introductions while a shopping link is paused.',category:'Filter by interest',any:'All interests',count:'brands',none:'No brands match this interest.',reset:'Show all brands',about:'About the brand',why:'Why it is in the edit',gallery:'A closer look at the selection',at:'Explore at',destination:'Product links open the brand’s website. Find the item and confirm the current details there.',delivery:'Before you order',source:'Read the source',checked:'Information checked',related:'You might also like',back:'Back to brands',disclosure:'Affiliate links: we may earn a commission at no extra cost to you. Purchases are completed on the brand’s website.',eventEmpty:'No active brand matches this event yet. Explore another occasion or remove the event filter.',eventIntro:'A few places to start, chosen for this occasion and your market.',concepts:'Editorial preview: the unbranded concepts below are inspiration, with shopping links still unavailable.',footer:'Selected brand links are affiliate links. Availability and delivery are confirmed by the retailer; this site remains a preview.',preview:'Preview status',
  },
  'de-de': {
    label:'Die Markenauswahl',title:'Gute Geschenke beginnen mit einer Entdeckung.',intro:'Entdecken Sie Marken nach Interessen. Lesen Sie unsere Vorstellung oder besuchen Sie den Shop direkt.',all:'Alle Marken entdecken',directoryTitle:'Finden Sie eine Marke, die passt.',directoryIntro:'Beauty, Wohnen, kreative Geschenke und praktische Ideen. Liefernachweise bestimmen die Reihenfolge, danach die redaktionelle Saisonpriorität.',visit:'Zum Markenshop',explore:'Marke entdecken',unavailable:'Dieser Markenlink ist vorübergehend nicht verfügbar.',available:'Marken entdecken',pending:'Pausierte Einkaufslinks',pendingIntro:'Die Vorstellungen bleiben bei pausiertem Einkaufslink lesbar.',category:'Nach Interesse filtern',any:'Alle Interessen',count:'Marken',none:'Für dieses Interesse gibt es noch keine Marken.',reset:'Alle Marken anzeigen',about:'Über die Marke',why:'Warum sie zur Auswahl gehört',gallery:'Die Auswahl näher ansehen',at:'Entdecken bei',destination:'Produktlinks öffnen den Markenshop. Suchen Sie dort den Artikel und prüfen Sie die aktuellen Angaben.',delivery:'Vor der Bestellung',source:'Quelle lesen',checked:'Informationen geprüft',related:'Das könnte Ihnen auch gefallen',back:'Zurück zu den Marken',disclosure:'Affiliate-Links: Wir können ohne Mehrkosten für Sie eine Provision erhalten. Der Kauf erfolgt im Markenshop.',eventEmpty:'Noch keine aktive Marke passt zu diesem Event. Anderen Anlass wählen oder den Eventfilter entfernen.',eventIntro:'Einige Anlaufstellen, passend zum Anlass und zu Ihrem Markt ausgewählt.',concepts:'Redaktionelle Vorschau: Die markenfreien Ideen unten dienen der Inspiration. Einkaufslinks sind noch nicht verfügbar.',footer:'Ausgewählte Markenlinks sind Affiliate-Links. Verfügbarkeit und Lieferung bestätigt der Händler; diese Website bleibt eine Vorschau.',preview:'Vorschaustatus',
  },
  'fr-fr': {
    label:'La sélection de marques',title:'Un beau cadeau commence par une découverte.',intro:'Découvrez des marques selon les centres d’intérêt. Lisez notre présentation ou rendez-vous directement sur leur site.',all:'Explorer toutes les marques',directoryTitle:'Trouvez une marque qui vous correspond.',directoryIntro:'Beauté, maison, cadeaux créatifs et idées pratiques. Les informations de livraison déterminent l’ordre, puis les priorités éditoriales de la saison.',visit:'Visiter la marque',explore:'Découvrir la marque',unavailable:'Ce lien de marque est temporairement indisponible.',available:'Marques à explorer',pending:'Liens d’achat en pause',pendingIntro:'Les présentations restent accessibles pendant la pause d’un lien.',category:'Filtrer par intérêt',any:'Tous les intérêts',count:'marques',none:'Aucune marque ne correspond à cet intérêt.',reset:'Afficher toutes les marques',about:'À propos de la marque',why:'Pourquoi elle figure dans la sélection',gallery:'La sélection de plus près',at:'Explorer chez',destination:'Les liens produits ouvrent le site de la marque. Retrouvez-y l’article et vérifiez les informations actuelles.',delivery:'Avant de commander',source:'Consulter la source',checked:'Informations vérifiées',related:'À découvrir aussi',back:'Retour aux marques',disclosure:'Liens affiliés : nous pouvons recevoir une commission sans coût supplémentaire pour vous. L’achat se termine sur le site de la marque.',eventEmpty:'Aucune marque active ne correspond à cet événement. Explorez une autre occasion ou retirez le filtre.',eventIntro:'Quelques pistes choisies pour cette occasion et votre marché.',concepts:'Aperçu éditorial : les idées sans marque ci-dessous servent d’inspiration. Les liens d’achat ne sont pas encore disponibles.',footer:'Certains liens de marques sont affiliés. Le marchand confirme disponibilité et livraison ; ce site reste un aperçu.',preview:'Statut de l’aperçu',
  },
} satisfies Record<Locale,Record<string,string>>
export const brandCategoryLabels: Record<Locale,Record<BrandCategory,string>> = {
  'en-gb':{beauty:'Beauty','self-care':'Self-care',fashion:'Fashion',home:'Home',personalised:'Personalised gifts',creative:'Creative gifts',hobby:'Hobbies & art',tech:'Practical tech'},
  'de-de':{beauty:'Beauty','self-care':'Self-Care',fashion:'Mode',home:'Wohnen',personalised:'Persönliche Geschenke',creative:'Kreative Geschenke',hobby:'Hobbys & Kunst',tech:'Praktische Technik'},
  'fr-fr':{beauty:'Beauté','self-care':'Bien-être',fashion:'Mode',home:'Maison',personalised:'Cadeaux personnalisés',creative:'Cadeaux créatifs',hobby:'Loisirs & art',tech:'Tech pratique'},
}
