import type { Currency, Locale, Market } from './types'

export const localeConfig: Record<Locale, { languageTag: string; label: string; market: Market; currency: Currency; symbol: string }> = {
  'en-gb': { languageTag: 'en-GB', label: 'United Kingdom · English', market: 'GB', currency: 'GBP', symbol: '£' },
  'de-de': { languageTag: 'de-DE', label: 'Deutschland · Deutsch', market: 'DE', currency: 'EUR', symbol: '€' },
  'fr-fr': { languageTag: 'fr-FR', label: 'France · Français', market: 'FR', currency: 'EUR', symbol: '€' },
}

export const isLocale = (value: string | undefined): value is Locale => Boolean(value && value in localeConfig)

export const ui = {
  'en-gb': {
    currentEvent: 'Current event', gifts: 'Gifts', women: 'Women', family: 'Family & kids', guides: 'Guides', brands: 'Brands', findGift: 'Find a gift',
    disclosure: 'Independent edit. Some links may earn us a commission at no extra cost to you.',
    exploreEvent: 'Explore the event', finderLabel: 'A quicker way to choose', finderTitle: 'Start with the person, not the product.', finderCopy: 'Find brands by recipient, interest and occasion. Check current prices and delivery with the brand.',
    phases: 'The seasonal rhythm', phaseTitle: 'Shop when it makes sense for you.', editorPicks: "Editor's preview", editorTitle: 'The shape of the edit.', womenTitle: 'For her, without the guesswork.', familyTitle: 'Family gifts, chosen by grown-ups.', budget: 'Shop by budget', upcoming: 'Coming next', guideTitle: 'Gift guides & shopping advice.', principles: 'How we choose', trustTitle: 'A calmer way to shop the season.',
    preview: 'Preview listing', pending: 'Partner link coming soon', checked: 'Editorial preview', bestFor: 'Best for', footerLine: 'Seasonal discovery with context, not noise.',
    interests:'Browse by interest',interestTitle:'A little discovery, around what they love.',allGuides:'All guides',useful:'Useful first',usefulCopy:'We start with the recipient and use case, not the commission.',marketAccurate:'Delivery with context',marketCopy:'Brand links are approved; destination, model and fulfilment still need checking with the retailer.',commercial:'Clearly commercial',commercialCopy:'Affiliate relationships are disclosed next to shopping choices.',now:'Right now',eventDate:'Event date for this market',eventContext:'Event phases guide preparation; they do not promise offers, stock or delivery.',deliveryTitle:'Delivery, with context.',deliveryCopy:'Check destination, dispatch and delivery estimates with the brand. No delivery deadline is guaranteed here.',skip:'Skip to content',navigation:'Primary navigation',explore:'Explore',policies:'Policies',editorialPolicy:'Editorial policy',privacy:'Privacy',affiliatePolicy:'Affiliate disclosure',privacyPreferences:'Privacy preferences',workingTitle:'Working title',madeFor:'Made for UK · Germany · France',credits:'Animation credits',privacyOptions:'Privacy options',choice:'Your choice, clearly.',noMeasurement:'No advertising or analytics service is configured in this preview.',essential:'Essential only',allow:'Allow measurement',reviewPending:'Local language and legal review is pending.',updated:'Updated',sources:'Sources',reading:'min read',relatedBrands:'Brands mentioned in this guide',savedFilters:'Your selections stay in the URL, so you can save or share the shortlist.',
  },
  'de-de': {
    currentEvent: 'Aktuelles Event', gifts: 'Geschenke', women: 'Für sie', family: 'Familie & Kinder', guides: 'Ratgeber', brands: 'Marken', findGift: 'Geschenk finden',
    disclosure: 'Unabhängige Auswahl. Manche Links können uns eine Provision einbringen – ohne Mehrkosten für Sie.',
    exploreEvent: 'Event entdecken', finderLabel: 'Schneller auswählen', finderTitle: 'Beginnen Sie mit der Person, nicht mit dem Produkt.', finderCopy: 'Finden Sie Marken nach Person, Interesse und Anlass. Preise und Lieferung beim Anbieter prüfen.',
    phases: 'Der saisonale Rhythmus', phaseTitle: 'Kaufen Sie dann, wenn es für Sie sinnvoll ist.', editorPicks: 'Redaktionelle Vorschau', editorTitle: 'So wird die Auswahl aussehen.', womenTitle: 'Für sie – ohne Rätselraten.', familyTitle: 'Familiengeschenke, von Erwachsenen ausgewählt.', budget: 'Nach Budget', upcoming: 'Als Nächstes', guideTitle: 'Geschenkratgeber & Einkaufstipps.', principles: 'Unsere Auswahl', trustTitle: 'Ruhiger durch die Geschenksaison.',
    preview: 'Vorschau', pending: 'Partnerlink folgt', checked: 'Redaktionelle Vorschau', bestFor: 'Ideal für', footerLine: 'Saisonale Entdeckungen mit Kontext statt Lärm.',
    interests:'Nach Interesse entdecken',interestTitle:'Entdeckungen nach den Vorlieben der beschenkten Person.',allGuides:'Alle Ratgeber',useful:'Nutzen zuerst',usefulCopy:'Person und Verwendungszweck stehen vor der Provision.',marketAccurate:'Lieferung mit Kontext',marketCopy:'Markenlinks sind freigegeben; Zielort, Modell und Bereitstellung beim Anbieter prüfen.',commercial:'Klare Kennzeichnung',commercialCopy:'Affiliate-Beziehungen stehen direkt bei den Einkaufsmöglichkeiten.',now:'Aktuell',eventDate:'Datum des Events in diesem Markt',eventContext:'Die Phasen helfen bei der Planung, versprechen aber keine Angebote, Bestände oder Lieferung.',deliveryTitle:'Lieferung mit Kontext.',deliveryCopy:'Zielort, Versand und Lieferprognose beim Anbieter prüfen. Wir garantieren keine Lieferfrist.',skip:'Zum Inhalt springen',navigation:'Hauptnavigation',explore:'Entdecken',policies:'Richtlinien',editorialPolicy:'Redaktionelle Richtlinie',privacy:'Datenschutz',affiliatePolicy:'Affiliate-Hinweis',privacyPreferences:'Datenschutzeinstellungen',workingTitle:'Arbeitstitel',madeFor:'Für Großbritannien · Deutschland · Frankreich',credits:'Animationsnachweise',privacyOptions:'Datenschutzoptionen',choice:'Ihre Entscheidung, klar erklärt.',noMeasurement:'In dieser Vorschau ist kein Werbe- oder Analysedienst eingerichtet.',essential:'Nur erforderlich',allow:'Messung erlauben',reviewPending:'Sprachliche und rechtliche Prüfung vor Ort steht aus.',updated:'Aktualisiert',sources:'Quellen',reading:'Min. Lesezeit',relatedBrands:'Marken aus diesem Ratgeber',savedFilters:'Ihre Auswahl bleibt in der URL und lässt sich speichern oder teilen.',
  },
  'fr-fr': {
    currentEvent: 'Événement en cours', gifts: 'Cadeaux', women: 'Pour elle', family: 'Famille & enfants', guides: 'Guides', brands: 'Marques', findGift: 'Trouver un cadeau',
    disclosure: 'Sélection indépendante. Certains liens peuvent nous rémunérer, sans coût supplémentaire pour vous.',
    exploreEvent: "Explorer l'événement", finderLabel: 'Choisir plus vite', finderTitle: 'Commencez par la personne, pas par le produit.', finderCopy: 'Trouvez des marques selon la personne, ses intérêts et l’occasion. Vérifiez prix et livraison auprès de la marque.',
    phases: 'Le rythme de la saison', phaseTitle: 'Achetez au moment qui vous convient.', editorPicks: 'Aperçu éditorial', editorTitle: 'La sélection prend forme.', womenTitle: 'Pour elle, sans choisir au hasard.', familyTitle: 'Des cadeaux famille choisis par des adultes.', budget: 'Par budget', upcoming: 'À venir', guideTitle: "Guides cadeaux & conseils d’achat.", principles: 'Notre sélection', trustTitle: 'Une façon plus sereine de vivre la saison.',
    preview: 'Aperçu', pending: 'Lien partenaire à venir', checked: 'Aperçu éditorial', bestFor: 'Idéal pour', footerLine: 'Une sélection saisonnière avec du contexte, sans bruit.',
    interests:'Explorer par intérêt',interestTitle:'Des découvertes autour de ce qui lui plaît.',allGuides:'Tous les guides',useful:'L’utilité d’abord',usefulCopy:'La personne et l’usage passent avant la commission.',marketAccurate:'Livraison en contexte',marketCopy:'Les liens sont autorisés ; destination, modèle et modalités restent à vérifier auprès du marchand.',commercial:'Une relation claire',commercialCopy:'Les relations d’affiliation sont indiquées près des choix d’achat.',now:'En ce moment',eventDate:'Date de l’événement pour ce marché',eventContext:'Les phases aident à préparer, sans promettre offre, stock ou livraison.',deliveryTitle:'La livraison en contexte.',deliveryCopy:'Vérifiez destination, expédition et estimation auprès de la marque. Aucun délai n’est garanti ici.',skip:'Aller au contenu',navigation:'Navigation principale',explore:'Explorer',policies:'Politiques',editorialPolicy:'Politique éditoriale',privacy:'Confidentialité',affiliatePolicy:'Information d’affiliation',privacyPreferences:'Préférences de confidentialité',workingTitle:'Nom provisoire',madeFor:'Pour le Royaume-Uni · l’Allemagne · la France',credits:'Crédits des animations',privacyOptions:'Options de confidentialité',choice:'Votre choix, clairement.',noMeasurement:'Aucun service publicitaire ou analytique n’est configuré dans cet aperçu.',essential:'Essentiel uniquement',allow:'Autoriser la mesure',reviewPending:'La révision linguistique et juridique locale reste à effectuer.',updated:'Mis à jour',sources:'Sources',reading:'min de lecture',relatedBrands:'Marques citées dans ce guide',savedFilters:'Votre sélection reste dans l’URL pour l’enregistrer ou la partager.',
  },
} satisfies Record<Locale, Record<string, string>>

export const localPath = (locale: Locale, path = '') => `/${locale}/${path.replace(/^\//, '')}`

export const formatMoney = (amount: number, locale: Locale, currency: Currency) =>
  new Intl.NumberFormat(localeConfig[locale].languageTag, { style: 'currency', currency, maximumFractionDigits: 0 }).format(amount)

export const formatDate = (date: string, locale: Locale) =>
  new Intl.DateTimeFormat(localeConfig[locale].languageTag, { day: 'numeric', month: 'short', year: 'numeric' }).format(new Date(date))
