import {test,expect} from '@playwright/test'
import AxeBuilder from '@axe-core/playwright'
test('unauthenticated visitor cannot read private UI/assets/API',async({request})=>{
 for(const path of ['/_manage/','/_manage/admin.js','/_manage/admin.css','/_manage/api/bootstrap'])expect((await request.get(path)).status()).toBe(403)
})
test('owner UI forms, concurrency, links, preview states and four-view accessibility',async({page,request})=>{
 const response=await request.get('/__fixture__/token'),{jwt}=await response.json() as {jwt:string}
 await page.setExtraHTTPHeaders({'Cf-Access-Jwt-Assertion':jwt})
 const errors:string[]=[];page.on('pageerror',error=>errors.push(error.message))
 await page.goto('/_manage/');await expect(page.locator('#notice')).toContainText('Đã tải dữ liệu')
 await expect(page.getByRole('heading',{name:'Không gian quản trị'})).toBeVisible()
 await page.getByRole('button',{name:'Brands',exact:true}).click()
 await page.getByLabel('Brand',{exact:true}).selectOption('toybox')
 const summary=page.getByRole('textbox',{name:'Giới thiệu ngắn'}).first()
 await summary.fill('A reviewed local test brand description.')
 await page.getByRole('button',{name:'Lưu tất cả nháp'}).click();await expect(page.locator('#notice')).toContainText('v2')
 await page.getByRole('button',{name:'Events',exact:true}).click();await page.getByLabel('Event homepage').selectOption('holiday-2026')
 await page.getByRole('button',{name:'Lưu nháp',exact:true}).click();await expect(page.locator('#notice')).toContainText('v3')
 await page.getByRole('button',{name:'Links',exact:true}).click()
 await page.getByLabel('Cách chọn link A').selectOption('brand')
 await page.getByLabel('Slug: 4–64').fill('admin-local-campaign')
 await page.getByLabel('Tên campaign').fill('Local campaign test')
 await page.getByRole('button',{name:'Tạo redirect (landing cần publish)'}).click()
 await expect(page.getByRole('heading',{name:'Local campaign test',exact:true})).toBeVisible()
 const campaign=page.locator('section').filter({has:page.getByRole('heading',{name:'Local campaign test',exact:true})})
 await expect(campaign).toContainText('Landing chưa publish')
 await campaign.getByRole('button',{name:'Pause ngay'}).click()
 await expect(page.locator('section').filter({has:page.getByRole('heading',{name:'Local campaign test',exact:true})})).toContainText('paused')
 expect((await request.get('/r/admin-local-campaign',{maxRedirects:0})).status()).toBe(410)
 for(const width of [375,768,1024,1440]){
  await page.setViewportSize({width,height:900})
  for(const name of ['Tổng quan','Brands','Links','Events','Publish & History']){
   await page.getByRole('button',{name,exact:true}).click()
   expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
   expect((await new AxeBuilder({page}).analyze()).violations).toEqual([])
  }
  await page.screenshot({path:'docs/qa/admin-publish-'+width+'.png',fullPage:true,scale:'css'})
 }
 await page.getByRole('button',{name:'Publish nháp v3'}).click()
 await expect(page.locator('#notice')).toContainText('CI chưa cấu hình')
 expect(errors).toEqual([])
})

test('paste an unlisted affiliate URL, copy B, measure redirect, pause/resume/archive without publishing',async({page,request})=>{
 const {jwt}=await (await request.get('/__fixture__/token')).json() as {jwt:string}
 await page.setExtraHTTPHeaders({'Cf-Access-Jwt-Assertion':jwt})
 await page.addInitScript(()=>{Object.defineProperty(navigator,'clipboard',{value:{async writeText(value:string){document.documentElement.dataset.copied=value}}})})
 const errors:string[]=[];page.on('pageerror',error=>errors.push(error.message))
 await page.goto('/_manage/');await expect(page.locator('#notice')).toContainText('Đã tải dữ liệu')
 await page.getByRole('button',{name:'Links',exact:true}).click()
 await expect(page.getByLabel('Cách chọn link A')).toHaveValue('custom')
 await expect(page.getByLabel('Locale',{exact:true})).toHaveCount(0)
 await expect(page.getByLabel('Quốc gia khai báo')).toHaveCount(0)
 const target='https://unlisted-merchant.example/?ref=Exact%2FCODE&utm_source=MyCampaign#Products'
 await page.getByLabel('URL affiliate A').fill(target)
 await page.getByLabel('Slug: 4–64').fill('custom-ui-campaign')
 await page.getByRole('button',{name:'Tạo link B',exact:true}).focus()
 await page.keyboard.press('Enter')
 await expect(page.locator('#notice')).toContainText('Đã tạo link B: http://127.0.0.1:5392/r/custom-ui-campaign')
 const card=()=>page.locator('section').filter({has:page.getByRole('heading',{name:'custom-ui-campaign',exact:true})})
 await expect(card()).toContainText(target);await expect(card()).toContainText('không cần publish, không có landing')
 await card().getByRole('button',{name:'Sao chép link B',exact:true}).click()
 expect(await page.locator('html').getAttribute('data-copied')).toBe('http://127.0.0.1:5392/r/custom-ui-campaign')
 const redirected=await request.get('/r/custom-ui-campaign?url=https://wrong.example',{maxRedirects:0,headers:{'User-Agent':'Mozilla/5.0'}})
 expect(redirected.status()).toBe(302);expect(redirected.headers().location).toBe(target);expect(await redirected.text()).toBe('')
 await page.getByRole('button',{name:'Tổng quan',exact:true}).click()
 await expect(page.locator('.stat-row').filter({hasText:'custom-ui-campaign'})).toContainText('unlisted-merchant.example')
 await expect(page.locator('#screen')).not.toContainText('undefined')
 await page.getByRole('button',{name:'Links',exact:true}).click()
 for(const width of [375,768,1024,1440]){
  await page.setViewportSize({width,height:900})
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
  expect((await new AxeBuilder({page}).analyze()).violations).toEqual([])
  expect(await page.getByRole('button',{name:'Tạo link B',exact:true}).evaluate(el=>el.getBoundingClientRect().height)).toBeGreaterThanOrEqual(48)
  await page.screenshot({path:'docs/qa/custom-links-'+width+'.png',fullPage:true,scale:'css'})
  await page.locator('section').first().screenshot({path:'docs/qa/custom-links-form-'+width+'.png',scale:'css'})
 }
 await card().getByRole('button',{name:'Pause ngay'}).click();await expect(card()).toContainText('paused')
 expect((await request.get('/r/custom-ui-campaign',{maxRedirects:0})).status()).toBe(410)
 await card().getByRole('button',{name:'Resume'}).click();await expect(card()).toContainText('active')
 expect((await request.get('/r/custom-ui-campaign',{maxRedirects:0})).status()).toBe(302)
 page.once('dialog',dialog=>dialog.accept())
 await card().getByRole('button',{name:'Archive vĩnh viễn'}).click();await expect(card()).toContainText('archived')
 await page.getByLabel('URL affiliate A').fill(target);await page.getByLabel('Slug: 4–64').fill('custom-ui-campaign');await page.getByRole('button',{name:'Tạo link B',exact:true}).click()
 await expect(page.locator('#notice')).toContainText('Slug has already been used')
 await expect(page.getByLabel('URL affiliate A')).toHaveValue(target)
 expect(errors).toEqual([])
})
