import type {Locale,Market,SeasonalEvent} from '@/lib/types'
import {brandCategories} from '@/lib/types'
import {brandCopy,brandCategoryLabels} from '@/lib/brand-copy'
import {localPath,localeConfig,ui} from '@/lib/i18n'
import {findBrands,type BrandFinderCard,type BrandFinderFilters} from '@/lib/brand-finder'
const copy={
'en-gb':{who:'Who is it for?',interest:'What do they enjoy?',event:'Occasion',market:'Country for delivery checks',result:'Brands to explore',none:'No brand matches all your choices. Remove an individual filter or explore another occasion.',reset:'Reset filters',all:'Any',women:'Women',family:'Family',children:'Children — adults choosing',teens:'Teens — adults choosing',migration:'The finder now explores brands, not prices. Your old budget filter has been removed; check prices on the brand’s website.',nojs:'Interactive filters need JavaScript. All ten brands and their shopping links remain available below.',remove:'Remove',gb:'United Kingdom',de:'Germany',fr:'France'},
'de-de':{who:'Für wen ist es?',interest:'Was gefällt der Person?',event:'Anlass',market:'Land für Lieferprüfung',result:'Marken entdecken',none:'Keine Marke passt zu allen Kriterien. Einzelnen Filter entfernen oder anderen Anlass entdecken.',reset:'Filter zurücksetzen',all:'Alle',women:'Für sie',family:'Familie',children:'Kinder — Erwachsene wählen',teens:'Teenager — Erwachsene wählen',migration:'Der Finder sucht jetzt Marken statt Preise. Der frühere Budgetfilter wurde entfernt; Preise stehen beim Anbieter.',nojs:'Interaktive Filter benötigen JavaScript. Alle zehn Marken und ihre Einkaufslinks bleiben unten verfügbar.',remove:'Entfernen',gb:'Großbritannien',de:'Deutschland',fr:'Frankreich'},
'fr-fr':{who:'Pour qui ?',interest:'Quels sont ses goûts ?',event:'Occasion',market:'Pays pour vérifier la livraison',result:'Marques à découvrir',none:'Aucune marque ne correspond à tous vos choix. Retirez un filtre ou explorez une autre occasion.',reset:'Réinitialiser',all:'Tous',women:'Pour elle',family:'Famille',children:'Enfants — choix des adultes',teens:'Adolescents — choix des adultes',migration:'Le finder cherche désormais des marques, pas des prix. L’ancien filtre budget est retiré ; consultez les prix sur le site de la marque.',nojs:'Les filtres interactifs nécessitent JavaScript. Les dix marques et leurs liens restent disponibles ci-dessous.',remove:'Retirer',gb:'Royaume-Uni',de:'Allemagne',fr:'France'}
} as const
interface Props {catalog:Record<Market,BrandFinderCard[]>;priorities:Record<string,string[]>;events:SeasonalEvent[];locale:Locale;activeEventId:string}
export default function GiftFinder({catalog,priorities,events,locale,activeEventId}:Props){
const t=copy[locale],bt=brandCopy[locale],initial:BrandFinderFilters={recipient:'all',category:'all',event:'all',market:localeConfig[locale].market}
const filters=initial,ready=false,migrated=false
const results=findBrands(catalog[filters.market],filters,priorities[activeEventId]||[],locale)
const chips=(key:'recipient'|'category',values:Array<[string,string]>)=>values.map(([label,value])=><button key={value} className={'finder-chip '+(filters[key]===value?'is-active':'')} type="button" aria-pressed={filters[key]===value} disabled={!ready} data-filter-key={key} data-filter-value={value}>{label}</button>)
return <div className="finder" data-ready={ready}><div className="finder__filters">
<fieldset><legend>01 · {t.who}</legend><div>{chips('recipient',[[t.all,'all'],[t.women,'women'],[t.family,'family'],[t.children,'children'],[t.teens,'teens']])}</div></fieldset>
<fieldset><legend>02 · {t.interest}</legend><div>{chips('category',[[t.all,'all'],...brandCategories.map(category=>[brandCategoryLabels[locale][category],category] as [string,string])])}</div></fieldset>
<label className="finder-select">03 · {t.event}<select value={filters.event} disabled={!ready} data-filter-key="event"><option value="all">{t.all}</option>{events.map(event=><option key={event.id} value={event.id}>{event.name[locale]}</option>)}</select></label>
<label className="finder-select">04 · {t.market}<select value={filters.market} disabled={!ready} data-filter-key="market"><option value="GB">{t.gb}</option><option value="DE">{t.de}</option><option value="FR">{t.fr}</option></select></label>
</div><div className="finder__result"><div className="finder__result-head"><div><span data-result-count>{results.length}</span><h2>{t.result}</h2></div><button type="button" disabled={!ready} data-finder-reset>{t.reset}</button></div>
<p role="status" className="finder-migration" hidden={!migrated}>{t.migration}</p><p className="muted">{bt.disclosure}</p><div data-finder-live role="status" aria-live="polite" className="sr-only">{results.length} {bt.count}</div>
<div className="finder__empty" hidden={results.length>0}><p>{t.none}</p><div className="chip-row">{(['recipient','category','event'] as const).map(key=><button type="button" className="button button--secondary" key={key} data-remove-filter={key} hidden={filters[key]==='all'}>{t.remove}: {key==='recipient'?t.who:key==='category'?t.interest:t.event}</button>)}</div><nav>{events.map(event=><a key={event.id} className="text-link" data-finder-related-event={event.id} href={localPath(locale,'events/'+event.slug[locale]+'/')}>{event.name[locale]} →</a>)}</nav></div>
<div className="finder-brand-list">{results.map(card=>{const {profile,link,products}=card,product=products[0];if(!link)return null;const payload={targetType:'brand',brandId:profile.id,merchantId:link.merchantId,market:filters.market,locale,eventId:filters.event==='all'?activeEventId:filters.event,placement:'gift-finder-brand',trackingId:link.trackingId};return <article key={profile.id} data-brand-id={profile.id}>
{product&&<picture><source type="image/avif" srcSet={product.image.sources.map(source=>source.avif+' '+source.width+'w').join(', ')} sizes="160px"/><img src={product.image.src} width={product.image.width} height={product.image.height} loading="lazy" alt={product.imageAlt[locale]}/></picture>}
<p className="section-label">{brandCategoryLabels[locale][profile.category]}</p><h3>{profile.name}</h3><p>{profile.summary[locale]}</p><p className="finder-fulfilment" data-fulfilment={card.fulfilment.status}>{card.fulfilment.note[locale]}</p><div className="finder-brand-actions"><a className="button button--primary" aria-label={bt.visit+': '+profile.name} href={link.affiliateUrl} rel="sponsored nofollow" data-affiliate-url={link.affiliateUrl} data-expires-at={link.expiresAt} data-affiliate={JSON.stringify(payload)}>{bt.visit} ↗</a><a className="button button--secondary" href={localPath(locale,'brands/'+profile.slug+'/')}>{bt.explore} →</a></div></article>})}</div><p className="muted">{ui[locale].deliveryCopy}</p></div></div>
}
